### ISSUE TITLE
`install.sh` skips unfinished downloads

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/vip#335]
**Describe the bug**
If during downloading a file `install.sh` gets interrupted, next time `install.sh` is executed, the partially downloaded file is skipped instead of the download being continued or retried.

**To Reproduce**
1. Run `bash vip/install.sh`
2. Press keyboard buttons for Keyboard interrupt (ctrl+c) 
3. Run `bash vip/install.sh` again

**Expected behavior**
Already present downloads are validated whether they are correct, and if not, downloaded again.

**Additional context**
Suggested solution would be to include a `checksums.csv` to validate already existing files and also check every file once all downloads have finished. To do this, it would be best to use a algorithm different than MD5, as this one is not secure anymore. See https://en.wikipedia.org/wiki/Secure_Hash_Algorithms for an overview of different options. While a SHA512 or an SHA3 option would be best, not sure how broad the support for these are out of the box. SHA256 might be supported on more systems by default while still offering more security than MD5 in case of the server being compromised.

Alternative solution is letting `wget --continue` figure out whether a download was finished, though this is less robust.

**Comment by dennishendriksen** [comment]
Fixed in https://github.com/molgenis/vip/pull/540
