### ISSUE TITLE
Script fails when trying to run from a different directory.

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/vip#40]
### Describe the bug
The `pipeline.sh` script fails when running it from a different directory.

#### v1.0.0
Directory structure used when encountering issue:
```
vip
|- vip-1.0.0
  |- pipeline.sh
  |- pipeline_0_preprocess.sh
  \- etc.
\- out
```
1. Make sure you are in the `vip` folder.
2. `sbatch --constraint=tmp01 vip-1.0.0/pipeline.sh -i vip-1.0.0/test/data/test.vcf -o out/test1.vcf`

This results in the following error:
```bash
$ cat vip.err
/var/spool/slurmd/job307828/slurm_script: line 195: ./pipeline_0_preprocess.sh: No such file or directory
```

#### master (584504842e2daa9d54f93195ebb5017ba4a1fe46)
Using the current master (commit: 584504842e2daa9d54f93195ebb5017ba4a1fe46) results in a slightly different `vip.err` (as it does not stop after the first error), but has the same problem:
```
$ cat vip.err
/var/spool/slurmd/job308894/slurm_script: line 12: utils/header.sh: No such file or directory
sh: ./pipeline_preprocess.sh: No such file or directory
sh: ./pipeline_annotate.sh: No such file or directory
sh: ./pipeline_filter.sh: No such file or directory
mv: cannot stat ‘/groups/umcg-gcc/tmp01/umcg-svandenhoek/vip/vip-master-2020-09-08/out3/out_pipeline_out/step2_filter//out.vcf’: No such file or directory
sh: ./pipeline_report.sh: No such file or directory
cp: cannot stat ‘/groups/umcg-gcc/tmp01/umcg-svandenhoek/vip/vip-master-2020-09-08/out3/out_pipeline_out/step4_report//out.html’: No such file or directory
```

### Expected behavior
Script runs independent of the directory from which it was executed.

### Additional context

A solution such as seen [here](https://github.com/molgenis/vibe/blob/719403ed21c0e471adae86fa9ab33c233bebc319/database/GenerateDatabase.sh#L33) might fix this. However, using `cd` to go to the script directory might break user-input paths if these are relative paths. Pre-pending the `${BASE_PATH}` to the used scripts might therefore be a better solution.

**Comment by dennishendriksen** [comment]
Alternative solution https://stackoverflow.com/a/246128

**Comment by svandenhoek** [comment]
Issue still exists (and now also occurs when running from the directory `pipeline.sh` is in). After digging a bit deeper into it, some possible solutions are mentioned on https://stackoverflow.com/a/57756247:
1. Revert #41 and add to README.md the **requirement** to `cd` to the directory containing the scripts first.
2. Set an environment variable that contains the path to the folder with all scripts and use that as the path (similar to EasyBuild `${EBROOTAPPNAME}` I suppose).
3. ~Create a "launcher" script~ (`#SBATCH` lines only work within launcher)

**Comment by svandenhoek** [comment]
Solution found based on: https://stackoverflow.com/a/56991068
