### ISSUE TITLE
Add functions to bash scripts

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/vip#45]
**Is your feature request related to a problem? Please describe.**
Currently when reading the bash scripts it's just a long list of everything what's done. This reduces the readability of the scripts. While the `echo` do indicate where each new step starts in `pipeline.sh`, stuff like command line parsing do not have their own "section" within the code.

**Describe the solution you'd like**
Dividing the separate steps done in a single script (such as every step in `pipeline.sh` and stuff like command-line parsing) into their own method would increase the readability of the scripts.

**Describe alternatives you've considered**
Adding additional comments. However, separate methods will look cleaner.

**Comment by dennishendriksen** [comment]
Fixed in https://github.com/molgenis/vip/pull/132
