### ISSUE TITLE
Add AlphaMissense to annotations

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/vip#514]
Running proteins algorithms ourselves to calculate the [ΔΔG](https://en.wikipedia.org/wiki/Gibbs_free_energy) of missense variation is tricky for a lot of reasons. But the next best thing is to use are the latest and greatest pre-calculated protein folding stability predictions, which is AlphaMissense, a deep learning model that builds on the protein structure prediction tool AlphaFold2.

The Science paper can be found here:
https://www.science.org/doi/10.1126/science.adg7492

Ensembl VEP plugin can be found here:
https://github.com/Ensembl/VEP_plugins/blob/release/110/AlphaMissense.pm

**Comment by dennishendriksen** [comment]
Moved to https://trac.molgeniscloud.org/ticket/10541
