### ISSUE TITLE
Web application not working

### ISSUE THREAD

**Issue by Taeriel** [molgenis/vip#650]
Good day

Please let me know if the VIP web application is not working?

I submitted a couple of jobs but just have "pending" under "status". It has been like this for some time.

Thanks

**Comment by dennishendriksen** [comment]
I've pinpointed the issue, which we will fix in the next iteration. In the mean time a workaround was used to process pending jobs, which should all have been processed by now.

**Comment by Taeriel** [comment]
Thanks very much. Since you have processed pending jobs, I submitted one
more job (the last one I need). I don't suppose you could process that one
too? I need it for a paper I'm finalising.

**Comment by Taeriel** [comment]
Oh never mind, it says it is running now.

Thank you!!!
